In [7]:
# exp7_1
import numpy as np
mat = np.random.randint(1,11,size=(3,3))
print(mat)
add=np.sum(mat)
print("\n Sum of Matrix is: ",add)


[[ 8  6  8]
 [ 9  2  4]
 [10  9  6]]

 Sum of Matrix is:  62


In [5]:
# exp7_2
import numpy as np
mat_1 = np.random.randint(1,11,size=(3,3))
print(mat_1)
avg=np.average(mat_1)
print("\nAverage of a Matrix is: ",avg)

[[2 3 2]
 [7 2 1]
 [8 8 5]]

Average of a Matrix is:  4.222222222222222


In [11]:
# exp7_3
import numpy as np
mat_1 = np.random.randint(1,11,size=(2,3))
print(mat_1)
add=np.sum(mat_1,axis=1)[1]
print("\nSum of First Row of Matrix is: ",add)


[[1 8 5]
 [9 2 1]]

Sum of First Row of Matrix is:  12


In [13]:
# exp7_4
import numpy as np
mat_1 = np.random.randint(1,11,size=(5,5))
print(mat_1)
max_1 = mat_1.max(axis=0)
print("\nMaximum values in each column is: ",max_1)

[[10  6  1  1  4]
 [ 8  3  8  8  8]
 [10  8  7  3  7]
 [ 3 10  2 10  9]
 [ 1  2  1  2  4]]

Maximum values in each column is:  [10 10  8 10  9]


In [19]:
# exp7_5
import numpy as np
max_1 = np.random.randint(1,11,size=(4,4))
print(max_1)
sum=0
for i in range(0,4):
    sum+=max_1[i][i]

print("\nSum of Diagonal elements is: ",sum)

[[10  6  8  6]
 [ 7  8 10  1]
 [ 7  4 10  3]
 [ 3 10  4 10]]

Sum of Diagonal elements is:  38


In [25]:
# exp7_6
import numpy as np
matx_1 = np.random.randint(1,11,size=(5,5))
print(matx_1)
max_1 = matx_1.min()
print("\nMinimum values in complete columns is: ",max_1)


[[ 6  3  7  7  3]
 [10  3  3  4  1]
 [ 4  5  9  8  2]
 [10  1  8  8  2]
 [ 9  6  8  6  5]]

Minimum values in complete columns is:  1


In [29]:
# exp7_7
import numpy as np
matx_1 = np.random.randint(1,21,size=(5,5))
print(matx_1)
sum=0
for i in range(0,4):
    for j in range(0,4):
        if matx_1[i][j]>10:
            sum+=matx_1[i][j]

print("\nSum of Elements greater than 10 is: ",sum)

[[12  1 14  5 14]
 [ 4 13  5  1  4]
 [15  8  3 15 11]
 [20 19 20 13  8]
 [ 7 17 13 20  5]]

Sum of Elements greater than 10 is:  141


In [31]:
# exp7_8
import numpy as np
mat_1 = np.random.randint(1,11,size=(5,5))
print(mat_1)
max_1 = mat_1.max(axis=1)
mean_1 = max_1.mean()
print("\nMean of Maximum values in each row is: ",mean_1)

[[ 3  4  2  9  1]
 [ 7  5  7  9  1]
 [ 4  6  8 10  7]
 [ 9  6  4  2  7]
 [ 6  7  5  1  1]]

Mean of Maximum values in each column is:  8.8


In [35]:
# exp7_9
import numpy as np
mat_1 = np.random.randint(1,11,size=(3,3))
print(mat_1)
add_1 =np.sum(mat_1,axis=1)[0]
add_2=np.sum(mat_1,axis=1)[2]
diff = add_1 - add_2
print("\nDifference between sum of first row and last row is: ",diff) 

[[9 2 2]
 [9 4 3]
 [3 2 9]]

Difference between sum of first row and last row is:  -1


In [53]:
# exp7_10
import numpy as np
mat_1 = np.random.randint(1,11,size=(6,6))
print(mat_1)
med_1 = np.median(mat_1)
print("\nmedian is: ",med_1)

for i in range(0,6):
    for j in range(0,6):
        if mat_1[i][j]<med_1:
            mat_1[i][j]=0
        else:
            mat_1[i][j]=mat_1[i][j]

print("\n",mat_1)

[[9 1 2 4 6 5]
 [6 7 3 6 9 2]
 [7 2 4 2 5 7]
 [8 1 2 1 1 4]
 [4 5 1 6 2 9]
 [9 8 3 3 5 8]]

median is:  4.5

 [[9 0 0 0 6 5]
 [6 7 0 6 9 0]
 [7 0 0 0 5 7]
 [8 0 0 0 0 0]
 [0 5 0 6 0 9]
 [9 8 0 0 5 8]]


In [61]:
# exp7_11
import numpy as np
up_tri_mat = np.triu(np.random.randint(1, 10, size=(4, 4)))
print(up_tri_mat)
sum_1 = np.sum(up_tri_mat)
print("\nSum of upper triangular matrix is: ",sum_1)

[[8 2 4 6]
 [0 9 8 3]
 [0 0 5 8]
 [0 0 0 6]]

Sum of upper triangular matrix is:  59


In [63]:
# exp7_12
import numpy as np
gen = np.random.randint(1,11,size=(3,4))
print(gen)
std_dev = gen.std(axis=0)[2]
print("\nstandard deviation of third column is: ",std_dev)

[[ 5  6  3  5]
 [ 3  3 10  5]
 [ 5  9  8  1]]

standard deviation of third column is:  2.943920288775949
