In [5]:
# exp8_1
import numpy as np
data = np.array([3,6,9,12,15])
mean_1=np.mean(data)
print(f"Mean: {mean_1}")

Mean: 9.0


In [7]:
# exp8_2
import numpy as np
data_1= np.array([7,3,9,1,5])
median_1 = np.median(data_1)
print(f"Median: {median_1}")


Median: 5.0


In [11]:
# exp8_3
import numpy as np
from scipy import stats as st
data_1= np.array([4,1,2,2,3,4,4])
mode_1 = st.mode(data_1)
print(f"Mode: {mode_1}")


Mode: ModeResult(mode=4, count=3)


In [9]:
# exp8_4
import numpy as np
ex_1= np.array([2,4,4,4,5,5,7,9])
var_1 = np.var(ex_1)
print(f"Variance: {var_1}")

Variance: 4.0


In [22]:
# exp8_5
import numpy as np
a=np.array([10,12,23,23,16,23,21,16])
std_1 = np.std(a)
print(f"Standard deviation: {std_1}")

Standard deviation: 4.898979485566356


In [24]:
# exp8_6
import numpy as np
arr1 = np.array([3,7,8,5,12,14,21,13,18])
range_1 = np.max(arr1)-np.min(arr1)
print(f"Range is: {range_1}")

Range is: 18


In [25]:
# exp8_7
import numpy as np
arr1=np.array([1,2,3,4,5])
arr2=np.array([2,4,6,8,10])

n=len(arr1)
sum_arr1 = np.sum(arr1)
sum_arr2 = np.sum(arr2)
sum_ar1_ar2 = np.sum(arr1*arr2)
sum_arr1_sq = np.sum(arr1**2)
sum_arr2_sq = np.sum(arr2**2)

num = n*sum_ar1_ar2-sum_arr1*sum_arr2
deno = np.sqrt((n*sum_arr1_sq - sum_arr1**2)*(n*sum_arr2_sq - sum_arr2**2))
coeff = num/deno
print("coefficient of Pearson's: ",coeff)
print(n)
print(sum_arr1)
print(sum_arr1_sq)


coefficient of Pearson's:  1.0
5
15
55


In [7]:
# exp8_8
import numpy as np
print(np.zeros(20))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [19]:
# exp8_9
import numpy as np
a = np.identity(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [21]:
# exp8_10
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
dot_1 = np.dot(arr1,arr2)
print(dot_1)

32


In [23]:
# exp8_11
import numpy as np
arr1=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
reshape_1 = arr1.reshape(3,4)
print(reshape_1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
